admin/models/Register.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "register".
 *
 * @property int $id
 * @property string $full_name
 * @property string $contact
 * @property string $email
 * @property int $fk_province
 * @property int $fk_district
 * @property int $fk_local_level
 * @property string $service_sector
 * @property string $org_name
 * @property string $org_sector_from
 * @property string|null $designation
 * @property string $info_source
 * @property string $meal_type
 * @property string $qr_code
 * @property string $otp
 * @property string $created_date
 * @property int $status
 */
class Register extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'register';
    }
    
    public $captcha;

    /**
     * {@inheritdoc}
     */
    const SUB_METROPOLITAN = 1;
    const MUNICIPALITY = 2;
    const RURAL_MUNICIPALITY = 3;
    const SAHAKARI = 4;
    const PABSON = 5;
    const NPABSON = 6;
    const OTHER = 7;
    const VEG = 7;
    const NON_VEG = 8;
    const SUBMITTED = 1;
    const VERIFIED = 2;
    const APPROVED = 3;
    const SOCIAL_MEDIA = 1;
    const NEWS_SITE = 2;
    const FRIENDS = 3;

    public function rules() {
        return [
            [['full_name', 'contact', 'email', 'fk_province', 'fk_district', 'fk_local_level', 'service_sector', 'org_name', 'org_sector_from', 'info_source', 'meal_type', 'otp', 'created_date', 'status'], 'required'],
            [['fk_province', 'fk_district', 'fk_local_level', 'status'], 'integer'],
            [['created_date', 'info_source', 'qr_code'], 'safe'],
            [['full_name', 'org_name', 'org_sector_from', 'designation'], 'string', 'max' => 100],
            [['contact'], 'number'],
            [['email'], 'email'],
            [['contact'],'unique', 'message' => 'Your Contact Number is already exist.'],
            [['email'], 'string', 'max' => 50],
            [['captcha'], 'captcha', 'message' => 'Captcha does not matched'],
            [['service_sector', 'meal_type'], 'string', 'max' => 20],
            [['otp'], 'number'],
           // [['info_source'], 'string', 'max' => 200],
           // [['qr_code'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'full_name' => 'Full Name',
            'contact' => 'Contact',
            'email' => 'Email',
            'fk_province' => 'Province',
            'fk_district' => 'District',
            'fk_local_level' => 'Local Level',
            'service_sector' => 'Service Sector',
            'org_name' => 'Organization Name',
            'org_sector_from' => 'Organization Sector From',
            'designation' => 'Designation',
            'info_source' => 'From where did you know about Event?',
            'meal_type' => 'Meal Type',
            'qr_code' => 'Qr Code',
            'otp' => 'Otp',
            'created_date' => 'Created Date',
            'status' => 'Status',
        ];
    }

    public static function getSectorFrom() {
        return [
            self::SUB_METROPOLITAN => 'Sub Metropolitan',
            self::MUNICIPALITY => 'Municipality',
            self::RURAL_MUNICIPALITY => 'Rural Municpality',
            self::SAHAKARI => 'Sahakari',
            self::PABSON => 'PABSON',
            self::NPABSON => 'NPABSON',
            self::OTHER => 'Other'
        ];
    }
    
    public function getProvince(){
        return $this->hasOne(Province::className(), ['id'  =>'fk_province']);
    }
    
    public function getDistrict(){
        return $this->hasOne(District::className(), ['id' => 'fk_district']);
    }
    
    public function getMunicipals(){
        return $this->hasOne(Municipals::className(), ['id' => 'fk_local_level']);
    }
}

admin/controllers/RegisterController.php
<?php

namespace app\controllers;

use app\models\Register;
use yii\filters\AccessControl;
use app\models\RegisterSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Da\QrCode\QrCode;
use yii\web\ForbiddenHttpException;
use Yii;

/**
 * RegisterController implements the CRUD actions for Register model.
 */
class RegisterController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [   
                    'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'view', 'delete', 'scan', 'print-all'],
                'rules' => [
                    [
                       // 'actions' => ['index', 'update', 'view', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Register models.
     *
     * @return string
     */
    public function actionIndex() {
        $searchModel = new RegisterSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Register model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Register model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Register();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->created_date = date('Y-m-d');
                $model->status = Register::SUBMITTED;
                $model->otp = rand(100000, 999999);
                $model->info_source = implode(",", $model->info_source); 
                throw new ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));die;
                $val = Register::find()->where(['contact' => $model->contact])->One();
                if ($val) {

                    if ($val->status == 1) {
                         Yii::$app->db->createCommand()
                                ->update('register', ['otp' => $model->otp])
                                ->execute();
                      $message = $model->otp . " This is your OTP for Registration for Digital Summit 2022 \n Powered By TUKI";
                      $to = $model->contact;
                      $ch = curl_init();
                      curl_setopt($ch, CURLOPT_URL, 'http://app.easy.com.np/easyApi');
                      curl_setopt($ch, CURLOPT_HEADER, 0);
                      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                      curl_setopt($ch, CURLOPT_POST, 1);
                      $data = array(
                      'key' => 'EASY5c406d30cb33d0.12577082',
                      'source' => 'none', // for default sender ID
                      'message' => $message,
                      'destination' => $to, // with or without country code
                      'type' => 1,
                      );

                      curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                      $contents = curl_exec($ch);
                        Yii::$app->session->setFlash('error', "Your Registration Submitted but not Verified.");
                        return $this->redirect(['verify', 'id' => $val->id]);
                    } else if ($val->status == 2  OR $val->status == 3) {
                        Yii::$app->session->setFlash('error', "Sorry !!! Your contact number is already exist.");
                        // return $this->redirect(['create']); 
                        $model->loadDefaultValues();
                    }
                    return $this->render('create', [
                                'model' => $model,
                    ]);
                }
             /*   $qrCode = (new QrCode('Guest Name: ' . $model->full_name . 'Contact:' . $model->contact . '<br> Organization Name: ' . $model->org_name))
                        ->setSize(250)
                        ->setMargin(5)
                        ->useForegroundColor(0, 0, 0); */
                
// now we can display the qrcode in many ways
// saving the result to a file:
            /*    $image_name = uniqid();
                $qrCode->writeFile('img/' . $image_name . '.png'); // writer defaults to PNG when none is specified

             * // display directly to the browser 
             */
//  header('Content-Type: ' . $qrCode->getContentType());
//echo $qrCode->writeString();
// echo '<img src="' . $qrCode->writeDataUri() . '">';
            //    $model->qr_code = 'img/' . $image_name . '.png';
                if ($model->save(false)) {
                    $message = $model->otp . " This is your OTP for Registration for Digital Summit 2022 \n Powered By TUKI";
                    $to = $model->contact;
                    $ch = curl_init();
                    curl_setopt($ch, CURLOPT_URL, 'http://app.easy.com.np/easyApi');
                    curl_setopt($ch, CURLOPT_HEADER, 0);
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                    curl_setopt($ch, CURLOPT_POST, 1);
                    $data = array(
                        'key' => 'EASY5c406d30cb33d0.12577082',
                        'source' => 'none', // for default sender ID
                        'message' => $message,
                        'destination' => $to, // with or without country code
                        'type' => 1,
                    );

                    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                    $contents = curl_exec($ch); 
                    return $this->redirect(['verify', 'id' => $model->id]);
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Register model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionVerify($id) {
        $model = $this->findModel($id);
        $otp = $model->otp;
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $verification_otp = $model->otp;
                if ($otp === $verification_otp) {
                    $model->status = 2;
                    $model->update(false);
                    Yii::$app->session->setFlash('success', "Your Registration Successfully Verified.");
                    return $this->redirect(['create']);
                } else {
                    Yii::$app->session->setFlash('error', 'Verification code does not matched');
                    return $this->redirect(['verify', 'id' => $id]);
                }
            }
        }
        return $this->render('verify');
    }
    
    public function actionOtpVerify($id){
        $model = $this->findModel($id);
        $model->status = 2;
        $model->update(false);
        Yii::$app->session->setFlash('success', 'Successfully otp verified by Admin');
        return $this->redirect(['index']);
    }

    public function actionApprove($id){
        $model = $this->findModel($id);
        $model->status = 3;
        $model->update(false);
        $message = "Your participation has been accepted in TUKI-Digital Summit in association with Ninja Infosys.
Program Details:
Date: 2078-12-28
Time: 9:00 am
Venue: Hotel Siddhartha Karnando
Please collect your ID card at registration desk at venue.
For more details:
9855047033
9858023662
SMS Powered By TUKI";
                    $to = $model->contact;
                    $ch = curl_init();
                    curl_setopt($ch, CURLOPT_URL, 'http://app.easy.com.np/easyApi');
                    curl_setopt($ch, CURLOPT_HEADER, 0);
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                    curl_setopt($ch, CURLOPT_POST, 1);
                    $data = array(
                        'key' => 'EASY5c406d30cb33d0.12577082',
                        'source' => 'none', // for default sender ID
                        'message' => $message,
                        'destination' => $to, // with or without country code
                        'type' => 1,
                    );

                    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                    $contents = curl_exec($ch); 
        Yii::$app->session->setFlash('success', 'Successfully Approved for Digital Summit');
        return $this->redirect(['index']);
    }
    
     public function actionPrint($id){
        $model = $this->findModel($id);
        return $this->render('print', [

admin/views/register/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RegisterSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="register-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'full_name') ?>

    <?= $form->field($model, 'contact') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'fk_province') ?>

    <?php // echo $form->field($model, 'fk_district') ?>

    <?php // echo $form->field($model, 'fk_local_level') ?>

    <?php // echo $form->field($model, 'service_sector') ?>

    <?php // echo $form->field($model, 'org_name') ?>

    <?php // echo $form->field($model, 'org_sector_from') ?>

    <?php // echo $form->field($model, 'designation') ?>

    <?php // echo $form->field($model, 'info_source') ?>

    <?php // echo $form->field($model, 'meal_type') ?>

    <?php // echo $form->field($model, 'qr_code') ?>

    <?php // echo $form->field($model, 'otp') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/register/approved.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $query app\models\Register */
$this->title = 'Digital Summit';
//$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<style>
#w1{
padding-left: 750px;
}
.program {
width:100%;
}
/*@media only screen and (max-width: 750px) {*/
/*          ul li {*/
/*               padding: 0px;*/
/*           }*/
/*       }*/

</style>
<div class="container">
    <div class="col-md-6">
        <?php foreach($query as $value){ ?>
        <div class="card" style="width: 428px; height: 150px;">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        
                        <h6><strong>Name :</strong> <?= $value['full_name']; ?> </h6>
                        <h6><strong>Contact : </strong><?= $value['contact']; ?></h6>
                        <h6><strong>Organization : </strong><?= $value['org_name']; ?></h6>
                        <h6><strong>Status : </strong>
                            <?php if($value['status'] == 3){ 
                                echo "<label class='text-success'>Approved</label>";
                                 }else if($value['status'] == 2){ 
                                echo "<label class='text-primary'>Verified</label>";
                            } else if($value['status'] == 1){ 
                                echo "<label class='text-danger'>Submitted</label>";
                            }
                    ?></h6>
                   
                    </div>
                    
                </div><br>
                
            </div>
        </div>
        <br>
         <?php } ?>
    </div>
    
</div>

admin/views/register/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Register */

$this->title = 'Digital Summit';
//$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="register-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

admin/views/register/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
//use yii\grid\GridView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RegisterSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Registers';
$this->params['breadcrumbs'][] = $this->title;
Yii::$app->params['bsDependencyEnabled'] = false;
?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    h1, h2, h3{
        font-size: 14px;
    }
    table, th, td{
        font-size: 13px;
        height: 10px;
    }
    
    tr{
        padding: 0;
        height: 10px;
        margin: 0;
        line-height: 1;
    }
    p{
        font-size: 12px;
        
    }
    input[type="text"]{
        height: 30px;
        font-size: 13px;
    }
    input[name="RegisterSearch[contact]"]{
        width: 80px;
    }
    input[name="RegisterSearch[org_sector_from]"]{
        width: 160px;
    }
    
    select[name="RegisterSearch[status]"]{
        height: 30px;
    }
    table thead th th{
        width: 30px;
    }
    .action-column{
        width: 60px;
    }
     #w2{
                padding-left: 750px;
            }
            @media only screen and (max-width: 750px) {
               ul li {
                    padding: 0px;
                }
    }
    .navbar-brand{
        font-size: 20px;
        padding-top: 10px;
    }
    #w3-collapse{
        padding-left: 750px;
    }
    .logout{
        font-size: 16px;
    }
    ol li{
        font-size: 16px;
    }
    .btn{
        font-size: 16px;
    }
       
</style>
<div class="register-index">


    <p>
        <?= Html::a('Register', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Qr Scan', ['scan'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Print All', ['print-all'], ['class' => 'btn btn-warning'])?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'id'=>'grid-view',
        'bordered' => true,
        'striped' => true,
        // 'selectedColumns'=> [1, 2, 3, 4, 5], 
        'condensed' => false,
        'responsive' => true,
        'hover' => true,
        'floatHeader' => true,
      //  'showPageSummary' => true,
        'toolbar'=>['{toggleData}'],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<b style="font-weight:bold;margin-left:45%;">Register Report</b>',
        ],
        
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'full_name',
            'contact',
            'email:email',
           // 'fk_province',
            //'fk_district',
            //'fk_local_level',
            //'service_sector',
            'org_name',
            [
                'attribute' => 'org_sector_from',
                'value' => function($model){
        if($model->org_sector_from==1){
            return 'Sub Metroplitan';
                }else if($model->org_sector_from==2){
                  return 'Municipality';  
                }else if($model->org_sector_from==3){
                   return 'Rural Municipality'; 
                }
                else if($model->org_sector_from==4){
                    return 'Sahakari';
                }
                else if($model->org_sector_from==5){
                    return 'PABSON';
                }
                else if($model->org_sector_from==6){
                    return 'NPABSON';
                }
                else if($model->org_sector_from==7){
                    return 'Other';
                }
                }
            ],
            //'designation',
            //'info_source',
            //'meal_type',
          //  'qr_code',
            //'otp',
            //'created_date',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'filter' => [1 => 'Submitted', 2 =>'Verified', 3 => 'Approved'],
                'value' => function($model){
                if($model->status==1){
                    return '<label class="text-danger">Submitted</label>';
                }else if($model->status==2){
                    return '<label class="text-primary">Verified</label>';
                }else if($model->status==3){
                    return '<label class="text-success">Approved</label>';
                }
                }
            ],
            [
                'class' => ActionColumn::className(),
                'template' => '{view} {print}',
                'buttons' => [
                    'print' => function ($url, $model, $key) {
                        return Html::a('<i class="fa fa-print"></i>', ['register/print', 'id' => $model->id]);
                    }
                ],
            ],
        ],
    ]); ?>


</div>

admin/views/register/program.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Register */

$this->title = 'Digital Summit';
//$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    #w1{
        padding-left: 750px;
    }
    .program {
    width:100%;
}
     /*@media only screen and (max-width: 750px) {*/
     /*          ul li {*/
     /*               padding: 0px;*/
     /*           }*/
     /*       }*/
        
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
        <img class="program img-responsive" src="img/program_details.jpeg" alt="Digital Summit 2022 Program Details"/>
        
    </div>
    </div>
    
</div>

admin/views/register/qr.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Register */

$this->title = 'Digital Summit';
//$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="register-create">

    <?= $this->render('scan', [
        'model' => $model,
    ]) ?>

</div>

admin/views/register/scan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $model app\models\Register */
/* @var $form yii\widgets\ActiveForm */

Yii::$app->params['bsDependencyEnabled'] = false;
?>
<style>
    #w2{
                padding-left: 750px;
            }
            @media only screen and (max-width: 750px) {
               ul li {
                    padding: 0px;
                }
    }
    form div.required label.control-label:after {

        content:" * ";

        color:red;

    }
    .help-block{
        color: red;
    }
</style>
<div class="register-form">
   
    <?php 
    $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'contact')->textInput(['maxlength' => true]) ?>
        </div>

    </div>
   
    <br>
    <div class="form-group">
        <?= Html::submitButton('Validate Guest', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
<img style="width:100%;" src="img/partners.JPG" class="pull-left img-responsive">
</div>

admin/views/register/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Register */

$this->title = 'Update Register: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="register-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

admin/views/register/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Register */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Registers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<style>
    h1, h2, h3{
        font-size: 14px;
    }
    table, th, td{
        font-size: 13px;
        height: 10px;
    }


    tr{
        padding: 0;
        height: 10px;
        margin: 0;
        line-height: 1;
    }
    p{
        font-size: 12px;

    }

        #w1{
                padding-left: 750px;
            }
            @media only screen and (max-width: 750px) {
                li {
                    padding: 0px;
                }
            }
    

</style>
<div class="register-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php if($model->status == 2){ 
            echo Html::a('Approve', ['approve', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'confirm' => 'Are you sure to approve for Digital Summit?'
            ]
        ]); } else if($model->status==1){ 
            echo Html::a('Otp Verify', ['otp-verify', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'confirm' => 'Are you sure to verify otp?'
            ]
        ]); 
            
        } ?>
            <?php /* echo Html::a('Delete', ['delete', 'id' => $model->id], [
          'class' => 'btn btn-danger',
          'data' => [
          'confirm' => 'Are you sure you want to delete this item?',
          'method' => 'post',
          ],
          ]) */ ?>
    </p>
    <table class="table table-striped">
        <tr>
            <th>Full Name</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Province</th>
            <th>District</th>
            <th>Local Level</th>
            <th>Service Sector</th>
        </tr>
        <tr>
            <td><?= $model->full_name; ?></td>
            <td><?= $model->contact; ?></td>
            <td><?= $model->email; ?></td>
            <td><?= $model->province->province; ?></td>
            <td><?= $model->district->district; ?></td>
            <td><?= $model->municipals->name; ?></td>
            <td><?= $model->service_sector; ?>
            </td>
        </tr>
        <tr>
            <th>Organization Name</th>
            <th>Organization Sector From</th>
            <th>Designation</th>
            <th>From where did you know about Event?</th>
            <th>Meal Type</th>
            <th>Created Date</th>
            <th>Status</th>
        </tr>
        <tr>
            <td><?= $model->org_name; ?></td>
            <td><?php
                if ($model->org_sector_from == 1) {
                    echo 'Sub Metroplitan';
                } else if ($model->org_sector_from == 2) {
                    echo 'Municipality';
                } else if ($model->org_sector_from == 3) {
                    echo 'Rural Municipality';
                } else if ($model->org_sector_from == 4) {
                    echo 'Sahakari';
                } else if ($model->org_sector_from == 5) {
                    echo 'PABSON';
                } else if ($model->org_sector_from == 6) {
                    echo 'NPABSON';
                } else if ($model->org_sector_from == 7) {
                    echo 'Other';
                }
                ?>
            </td>
            <td><?= $model->designation; ?></td>
            <td><?php
                $info_src = [];
                $info_src = explode(",", $model->info_source);
                $count = count($info_src);
                $social = "";
                $news = "";
                $frnds = "";
                $output = "";
                if ($count == 3) {
                    if ($info_src[0] == 1) {
                        $social = "Social Media";
                    }
                    if ($info_src[1] == 2) {
                        $news = "News Portal";
                    }
                    if ($info_src[2] == 3) {
                        $frnds = "Friends";
                    }
                    echo $social . " , " . $news . " , " . $frnds;
                } else if ($count == 2) {
                    if ($info_src[0] == 1) {
                        $social = "Social Media";
                    } else if ($info_src[0] == 2) {
                        $social = "News Portal";
                    } else if ($info_src[0] == 3) {
                        $social = "Friends";
                    }
                    if ($info_src[1] == 1) {
                        $news = "Social Media";
                    } else if ($info_src[1] == 2) {
                        $news = "News Portal";
                    } else if ($info_src[1] == 3) {
                        $news = "Friends";
                    }
                    echo $social . " , " . $news;
                } else if ($count == 1) {
                    if ($info_src[0] == 1) {
                        $output = "Social Media";
                    } else if ($info_src[0] == 2) {
                        $output = "News Portal";
                    } else if ($info_src[0] == 3) {
                        $output = "Friends";
                    }
                    echo $output;
                }
                ?>
            </td>
            <td><?php
                if ($model->meal_type == 7) {
                    echo "Veg";
                } else if ($model->meal_type == 8) {
                    echo "Non Veg";
                }
                ?>
            </td>
            <td><?=$model->created_date; ?></td>
            <td><?php
                if ($model->status == 1) {
                    echo '<label class="text-danger">Submitted</label>';
                } else if ($model->status == 2) {
                    echo '<label class="text-primary">Verified</label>';
                } else if ($model->status == 3) {
                    echo '<label class="text-success">Approved</label>';
                }
                ?></td>
        </tr>
    </table>
    
</div>